### PR TITLE
Update aws-sdk-go dependency to v1.38.22.

### PR DESCRIPTION
**Pull request by dhess**
This release includes AWS SSO support, among other things.

Updated via:

```
go get github.com/aws/aws-sdk-go@v1.38.22
go mod tidy
```

### CODE REVIEW

**Comment by dhess** [comment]
We've switched to Vault from Chamber, but since everyone was asking for an update to #294 (which uses an older AWS SDK that still supports AWS SSO), and the last one was so easy to do, I'll do one last PR as a parting gift ;)

**Comment by allixsenos** [comment]
"from Vault to Chamber" ?

(thank you!)

**Comment by allixsenos** [comment]
I can confirm these changes make AWS SSO work without the need for `aws-vault`

**Review by nickatsegment — APPROVED** [review]

**Comment by nickatsegment** [comment]
Awesome! Thanks.

**Pull request merged**
