### PR TITLE
Update aws-sdk-go dependency to v1.37.15.

### PR DESCRIPTION
**Pull request by dhess**
Updated via:

```
go get github.com/aws/aws-sdk-go@v1.37.15
go mod tidy
go mod vendor
```

This version of the SDK includes support for AWS SSO.

### CODE REVIEW

**Comment by nickatsegment** [comment]
Any particular features/fixes you're looking for from this update?

**Comment by nickatsegment** [comment]
I tried fixing the failed stuff, but decided to just upgrade go and get rid of vendoring. Please rebase :) and no need to do `go mod vendor`

**Comment by dhess** [comment]
Yes, as of this version, the Go SDK finally supports AWS SSO credentials, meaning that if you authenticate with AWS SSO, you no longer need a helper program like `aws-sso-credential-process` to make it work with Chamber :)

**Comment by nickatsegment** [comment]
@dhess awesome, sounds valuable to us as well. We're exploring AWS SSO, early days.

**Comment by wendtek** [comment]
+1 on looking for AWS SSO support

**Comment by allixsenos** [comment]
uhh... this caught us by surprise... any ETA on a release against the latest AWS SDK?

**Comment by dhess** [comment]
This PR was quite stale, so I just made a new one using the latest AWS SDK. I'll keep this open in case something goes wrong with the newest SDK version. (We've been using this one for several months with no issues.)

See https://github.com/segmentio/chamber/pull/304

**Comment by nickatsegment** [comment]
Superseded by #304

**Pull request closed without merging**
