### PR TITLE
Provide a noop environment variable to bypass chamber

### PR DESCRIPTION
**Pull request by ejcx**
Chamber users are clamboring for this feature. They really want to be able to
painless run chamber in development without needing to pass Env variables from
aws-vault to their container, and without needing any special bash-fu to make
things work.

Provide CHAMBER_NOOP to just execute whatever command is passed to chamber.

I think one improvement could be logging loudly if chamber is being run with
this flag set. This would make debugging production issues easier in case
CHAMBER_NOOP has been set in production.

### CODE REVIEW

**Comment by ejcx** [comment]
Sorry @dfuentes. I'm sure this is not a feature you are excited about, but running chamber locally has consistently been a pain point for people.

I made a small bash alias that passes aws-vault creds to docker so that chamber can authenticate as individuals, but people are not excited about it and really want chamber to just fix it

```
docker run \
  --env "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  --env "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  --env "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" \
  --env "AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN" \
  --env "AWS_VAULT=$AWS_VAULT" \
  --env "AWS_REGION=$AWS_REGION" \
  --env "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" \
  $1
```

Curious what your thoughts are.

**Comment by dfuentes** [comment]
Some issues I have with this approach:

1) Doesn't really solve the problem (as I understand it).  If an application requires a secret from chamber/parameter store to run, making chamber a no-op still doesn't solve the problem of applications needing that value.  The likely way a user would then solve the problem is making some local run script or make target that invokes their docker container with the proper env vars hard coded.

My guess is that we could standardize the local run process in a way that makes it easy for users to invoke chamber with the correct auth locally, making this a one line change that they can make without constantly updating a run script/make target.

2)  I would really like to avoid solutions that fork the runtime flow between "local" and "remote" runs of an application.  Having two different code/execution paths for these set ups make bugs more likely as things drift apart.

I think we should step back and really look at the problem and brainstorm some solutions, instead of jumping to this one.  We could do this in person, or maybe open a github issue and we can discuss possible solutions there.

**Comment by ejcx** [comment]
I don't think we actually need this anymore. If you are here, I have a shell script called `adr` in my `$HOME/bin` directory that has the following code

```
#!/bin/zsh
docker run \
  --env "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
  --env "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
  --env "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" \
  --env "AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN" \
  --env "AWS_VAULT=$AWS_VAULT" \
  --env "AWS_REGION=$AWS_REGION" \
  --env "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" \
  -it $1 /bin/sh
```

adr stands for authenticated docker run. I use it like this.

```
$ docker build .
.....
Created image d34db33f

$ aws-vault exec development -- adr d34db33f
```

**Comment by FernandoMiguel** [comment]
when using aws-vault, consider using the flag --server
this starts a daemon and will make it possible to run chamber from anywhere

(still requires  `export AWS_REGION=` )

**Pull request closed without merging**
