### PR TITLE
chore: installation for Go 1.18

### PR DESCRIPTION
**Pull request by mrkagelui**
addresses #349

### CODE REVIEW

**Comment by mrkagelui** [comment]
> Would it be too much to ask you to add 1.17.x and 1.18.x to the github action build matrix here: https://github.com/segmentio/chamber/blob/master/.github/workflows/build.yml#L14

certainly, if that's ok

**Comment by mrkagelui** [comment]
> Would it be too much to ask you to add 1.17.x and 1.18.x to the github action build matrix here: https://github.com/segmentio/chamber/blob/master/.github/workflows/build.yml#L14

how about `test` and `dist` though, should they be added or are they not supported?

**Comment by mrkagelui** [comment]
I'll just add and ask for forgiveness 😆

**Comment by asaf-erlich** [comment]
> how about test and dist though, should they be added or are they not supported?

My gut tells me to update those as well. I don't see any reason why they should fail. But I don't want to throw unnecessary work on you. Feel free to try it but if it fails don't worry about it.

**Comment by mrkagelui** [comment]
> > how about test and dist though, should they be added or are they not supported?
> 
> My gut tells me to update those as well. I don't see any reason why they should fail. But I don't want to throw unnecessary work on you. Feel free to try it but if it fails don't worry about it.

done, thanks for attending to this! I'm kinda surprised no one has encountered this yet.

**Comment by asaf-erlich** [comment]
Yup: https://go.dev/doc/go-get-install-deprecation:

>Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.

>In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will always act as if the -d flag were enabled.

**Comment by asaf-erlich** [comment]
I don't want to block your PR, you have a couple of options:

1. Just drop 1.18.x for now for the install.
2. Change it to use go install and hope that's backwards compatible for all the versions?

**Comment by mrkagelui** [comment]
I don't have other go version installed locally, so here's what I'm gonna try:

1. shoot in the dark and go with `install`;
2. if that fails, I'm gonna split the job into two, >1.17 and older, wdyt?

**Comment by asaf-erlich** [comment]
Alright everything passed except that dockerhub login which I think was broken before or is at least flaky, I'll approve the PR.

**Comment by asaf-erlich** [comment]
cc @rikez do you know why the docker hub login github action task fails? I remember it happened before for you

**Comment by rikez** [comment]
@asaf-erlich It is failing because secrets aren't available in repo forks. Basically, the job is attempting to log in to Docker Registry using empty login and password values.

This docker step should be removed from feature branches. Let me open a PR to remove it.

**Comment by rikez** [comment]
https://github.com/segmentio/chamber/pull/351

**Comment by mrkagelui** [comment]
@asaf-erlich would be great if we can get a new version of this so that installation is easier

**Comment by mrkagelui** [comment]
> @mrkagelui I will create a backlog ticket for the team to prioritize a new release.

awesome, thank you and the team for this great tool, lots of ❤️

**Pull request merged**
