### PR TITLE
Add support for darwin/arm64 (Apple Silicon M1)

### PR DESCRIPTION
**Pull request by chrisgoffinet**

### CODE REVIEW

**Comment by sindhusegment** [comment]
Hey @chrisgoffinet so this PR is very similar to another one merged recently: https://github.com/segmentio/chamber/pull/307

For this, if you wish to generate a new github release and also have a release to packagecloud, you would want to include `publish-github-darwin-arm64` on https://github.com/segmentio/chamber/blob/235234a72756ad6c71ddc7af6db89ad82f8435fa/Makefile.release#L33 and https://github.com/segmentio/chamber/blob/235234a72756ad6c71ddc7af6db89ad82f8435fa/Makefile.release#L35

**Comment by chrisgoffinet** [comment]
> Hey @chrisgoffinet so this PR is very similar to another one merged recently: #307
> 
> For this, if you wish to generate a new github release and also have a release to packagecloud, you would want to include `publish-github-darwin-arm64` on
> 
> https://github.com/segmentio/chamber/blob/235234a72756ad6c71ddc7af6db89ad82f8435fa/Makefile.release#L33
> 
> and
> https://github.com/segmentio/chamber/blob/235234a72756ad6c71ddc7af6db89ad82f8435fa/Makefile.release#L35

Thanks. I was just following the convention from prior commit. Might be a bug we don't push the linux-arm64, as thats how I missed that. I pushed up a change to include darwin-arm64 on github now.

**Comment by sindhusegment** [comment]
Yeah it is a bug - I've just created a PR for it: https://github.com/segmentio/chamber/pull/311
Not sure what the procedure is to get your PR approved but we're looking into it

**Comment by chrisgoffinet** [comment]
@sindhusegment does this look good now?

**Comment by sindhusegment** [comment]
> @sindhusegment does this look good now?

Hey @chrisgoffinet sorry for the delayed response on this. So we've actually got a linux-arm64 PR that we merged recently but we're having issues generating an arm64 release in CircleCI for both a github binary and a packagecloud debian release. Were you able to test to see if you can successfully build the package and release it? If you have, then this would be super helpful for us and it will move along both your release for darwin-arm64 and ours for linux-arm64

**Comment by eddeee888** [comment]
Hi @sindhusegment @chrisgoffinet , how are we going with this PR? What's needed to push this over the line? :)

**Comment by asaf-erlich** [comment]
cc @emmy-byrne-segment so you're aware of this PR as well ^^

**Review by emmy-byrne-segment — APPROVED** [review]

**Comment by emmy-byrne-segment** [comment]
This all seems correct to me. Doing some local checks before we merge.

**Comment by emmy-byrne-segment** [comment]
Tested with a rudimentary test on an M1 machine and build output is functional and correct arch.

**Comment by eddeee888** [comment]
Thank you so much! Does this mean the next release should have the arm64 version? If so, when would that be if you don't mind me asking?
In the meantime, if I need to use a specific binary, would the recommendation be to check this out and build the binaries locally? :)

**Pull request merged**
