### PR TITLE
fix: update yaml package to resolve vulnerabilities

### PR DESCRIPTION
**Pull request by paulwus**
update yaml package to v3.0.1 to resolve vulnerabilities

### CODE REVIEW

**Comment by rikez** [comment]
@paulwus Could you update the `go.sum`?

**Review by rikez — CHANGES_REQUESTED** [review]
Could you update the go.sum?

**Comment by paulwus** [comment]
@rikez  thanks! updated go.sum as requested.

**Comment by rikez** [comment]
@paulwus I think I found the issue related to this version: https://github.com/go-yaml/yaml/issues/665. Going to approve and merge your changes. Thank you for contributing!

**Review by rikez — APPROVED** [review]

**Pull request merged**
