### PR TITLE
+ None Backend

### PR DESCRIPTION
**Pull request by maartenvanderhoef**
# Adding None Backend
Adding a None Backend to make it easy to disable any kind of backend lookups. In some cases, especially during migrations it is not possible to simply disable Chamber by changing the command. To then put chamber inside a wrapper script is also quite cumbersome.

My suggestion is to add a None backend, which would simply passthrough ENV when the ENV variable `CHAMBER_SECRET_BACKEND` has been set to `NONE`.

### CODE REVIEW

**Comment by osterman** [comment]
@maartenvanderhoef is this also related to this? https://github.com/segmentio/chamber/issues/115

**Comment by maartenvanderhoef** [comment]
@osterman 100%

**Comment by nickatsegment** [comment]
Good stuff, how do we feel about the name? It's fine as is, but how about NoopBackend? Null? Fake? Mock?

**Comment by systemizer** [comment]
I think this is fine. I'm curious about the use cases for needing this functionality. 

For example, when you are running migrations, what is forcing you to run chamber when doing this? Maybe there is additional tooling that just requires you to run chamber nonetheless? I'm curious what the forcing function is here.

**Comment by maartenvanderhoef** [comment]
@systemizer I think you have migrations in mind like database migrations. what I meant is; migrating docker services from A to B. I explained it here: https://github.com/segmentio/chamber/issues/143

@nickatsegment Null was my second thought. Let me know what naming you like and I'll change it.

**Comment by systemizer** [comment]
@maartenvanderhoef thanks for the explanation. I can now see how using the same docker images w/ chamber across cloud providers can lead to difficulties.

I'm also leaning towards `NullStore`. how about we change None --> Null and then we merge?

**Comment by maartenvanderhoef** [comment]
Apologies, I made https://github.com/segmentio/chamber/pull/149 as I couldn't figure out how to leave my merge issues.

**Pull request closed without merging**
