### PR TITLE
Read subcommand: Read one secret at a time.

### PR DESCRIPTION
**Pull request by ejcx**

### CODE REVIEW

**Comment by sc-chad** [comment]
Sounds great to me!

**Comment by dfuentes** [comment]
Looks good, some additional flags that may be useful to add (although we could do it later):

`-v/--version <int>` to read a specific version of the secret
`-q/--quiet` Print only the secret, not the whole table/metadata

**Comment by sc-chad** [comment]
Both great suggestions.

**Comment by ejcx** [comment]
LGTM, what say you?

**Pull request merged**
